import type { Metadata } from "next";

import "@/app/globals.css";
import { cairo } from "@/app/fonts";

export const metadata: Metadata = {
  title: "مُختصِر | أول منتج عربي متكامل لإختصار الروابط",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${cairo.className} antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
