import type { Metadata } from "next";
import { Noto_Sans_Arabic } from "next/font/google";

import "./globals.css";

export const notoSans = Noto_Sans_Arabic({
  variable: "--primary-font",
  subsets: ["arabic"],
  preload: true,
  fallback: ["Noto Sans Arabic", "Tajawal", "Cairo", "Amiri", "Arial", "sans-serif"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${notoSans.className} antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
