import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/next"
import "@/app/globals.css";
import { cairo } from "@/app/fonts";
import { AuthProvider } from "@/features/auth/context/auth-context";
import { UrlProvider } from "@/features/urls/context/urls-context";

export const metadata: Metadata = {
  title: "مُختصِر | أول منتج عربي متكامل لإختصار الروابط",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${cairo.className} antialiased `}
      >
        <AuthProvider>
          <UrlProvider>
            {children}
            {/* <SpeedInsights /> */}
            {/* <Analytics /> */}
          </UrlProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
